### ISSUE TITLE
Where is Lytro dataset? and if it is suit for Lytro illum?

### ISSUE THREAD

**Issue by RennyZhao** [sgpobrien/PlenCalToolbox#1]

**Comment by sgpobrien** [comment]
Hi Zhao,

The Lytro Dataset used was made by Donald Dansereau, links are available on this page: https://dgd.vision/Tools/LFToolbox/. Note that these .raw files will need to be converted to .jpg or .png in order to be used with this toolbox. 

This calibration method has worked with a Lytro Illum camera. 

Cheers,
Sean

**Comment by RennyZhao** [comment]
Thanks for your reply. 
I have see your code, and also I compared with your reference paper [2] Y. Bok, H. G. Jeon, and I. S. Kweon. Geometric calibration of micro-lens-based light field cameras using line features. IEEE Transactions on Pattern Analysis and Machine Intelligence, 39(2):287–300, 2017.
Is the calculation of K2 is right? (please see the LINEAR_ESTIMATE_CALIBRATION_PARAMETERS.m). Your K2_(t)=v(12)/lambda_(t)-K1_(t)*v(3)/lambda_(t);  Is the last lambda_(t) is right? (please see the K2 calculation in reference [2]).

Look forward for your reply.
Cheers.
RennyZhao

**Comment by sgpobrien** [comment]
Yes, this appears correct. In that paper the equation is K_2 = v_12/lambda - K_1 t_3, but in ours it is K_2 = v_12/lambda - K_1 v_3/lambda, but note that t_3 = v_3/lambda. 

For more queries like this please contact me by email directly at sean.obrien@anu.edu.au. 

Cheers,
Sean
